version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --save 900 1 --appendonly yes
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_APPENDONLY=yes
      - REDIS_SAVE=900 1
  gooeylytics:
    build: .
    container_name: gooeylytics
    working_dir: /usr/app
    dns:
      - 1.1.1.1
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      # Passes credentials through from .env file at root of project
      - ALCHEMY_API_KEY
      - DISCORD_TOKEN
      - DISCORD_CLIENT
    restart: unless-stopped

  metadata-exporter:
    build:
      context: .
      target: run-export
    container_name: metadata-exporter
    profiles:
      - export
    volumes:
      - ./data:/usr/data
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://bot-redis:6379
    networks:
      - stateful-bot-stack_default
    

networks:
  stateful-bot-stack_default:
    external: true