version: '3'
services:
  gooeylytics:
    build: .
    container_name: gooeylytics
    working_dir: /usr/app
    dns:
      - 1.1.1.1
    environment:
      - NODE_ENV=production
    restart: unless-stopped